## @file spec_field.py
#  @brief Setup the SPEC magnetic field system for ODE solver
#  @author Zhisong Qu (zhisong.qu@anu.edu.au)
#  @author Chris Smiet (christopher.smiet@epfl.ch)

from .toroidal_bfield import ToroidalBfield
import pyoculus_spec_fortran_module as fortran_module
import numpy as np


## Class that used to setup the SPEC bfield problem for interfacing Fortran, used in ODE solver.
# See \ref specbfield for more details.
#
# The SPECBfield system of ODEs is given by
# \f[ \frac{ds}{d\zeta} = \frac{B^{s}}{B^{\zeta}}  \f]
# \f[ \frac{d\theta}{d\zeta} = \frac{B^{\theta}}{B^{\zeta}}  \f]
class SpecBfield(ToroidalBfield):
    ## the problem size, 2 for 1.5D/2D Hamiltonian system

    def __init__(self, spec_data, lvol):
        """! Set up the equilibrium for use of the fortran module
        @param spec_data the SPEC data generated by py_spec.SPECout
        @param lvol which volume we are interested in, from 1 to spec_data.input.Mvol
        Only support SPEC version >=3.0
        """
        super().__init__(1)  # argument 1 sets Nfp which is overwritten when module is initialized. 
        self._init_fortran_module(spec_data, lvol)
        self.problem_size = 2
        if self.Igeometry == 1:
            self.poincare_plot_type = "yx"
            self.poincare_plot_xlabel = r"$\theta$"
            self.poincare_plot_ylabel = r"R"
        elif self.Igeometry == 2:
            self.poincare_plot_type = "RZ"
            self.poincare_plot_xlabel = "X(m)"
            self.poincare_plot_ylabel = "Y(m)"
        elif self.Igeometry == 3:
            self.poincare_plot_type = "RZ"
            self.poincare_plot_xlabel = "R(m)"
            self.poincare_plot_ylabel = "Z(m)"
        else:
            raise ValueError("Unknown Igeometry!")

        ## The output of B contains the jacobian factor
        self.has_jacobian = True
    
    @classmethod
    def from_h5_file(cls, h5_file, lvol):
        """! Initialize the SPEC magnetic field from a SPEC h5 file
        @param h5_file the path to the SPEC h5 file
        @param lvol which volume we are interested in, from 1 to spec_data.input.Mvol
        Only support SPEC version >=3.0
        """
        from py_spec import SPECout
        spec_data = SPECout(h5_file)
        return cls(spec_data, lvol)


    def B(self, coords, *args):
        """! Returns magnetic fields
        @param coordinates \\f$(s,\\theta,\\zeta)\\f$
        @param *args extra parameters
        @returns the contravariant magnetic fields
        """

        return self.fortran_module.specbfield.get_bfield(coords)

    def dBdX(self, coords, *args):
        """! Returns magnetic fields
        @param coordinates \\f$(s,\\theta,\\zeta)\\f$
        @param *args extra parameters
        @returns B, dBdX, the contravariant magnetic fields, the derivatives of them
        """

        B, dB = self.fortran_module.specbfield.get_bfield_tangent(coords)
        return B, dB

    def B_many(self, x1arr, x2arr, x3arr, input1D=True, *args):
        """! Returns magnetic fields, with multipy coordinate inputs
        @param x1arr the first coordinates. Should have the same length as the other two if input1D=True.
        @param x2arr the second coordinates. Should have the same length as the other two if input1D=True.
        @param x3arr the third coordinates. Should have the same length as the other two if input1D=True.
        @param input1D if False, create a meshgrid with sarr, tarr and zarr, if True, treat them as a list of points
        @param *args extra parameters
        @returns the contravariant magnetic fields
        """
        x1arr = np.atleast_1d(x1arr)
        x2arr = np.atleast_1d(x2arr)
        x3arr = np.atleast_1d(x3arr)

        if not input1D:
            size = (x1arr.size, x2arr.size, x3arr.size)
            s = np.broadcast_to(x1arr[:, np.newaxis, np.newaxis], size).flatten()
            t = np.broadcast_to(x2arr[np.newaxis, :, np.newaxis], size).flatten()
            z = np.broadcast_to(x3arr[np.newaxis, np.newaxis, :], size).flatten()
            n = s.size
            Blist = self.fortran_module.specbfield.get_bfield_many_1d(s, t, z, n)
            Blist = np.reshape(Blist, (x1arr.size, x2arr.size, x3arr.size, 3))
        else:
            n = x1arr.size
            Blist = self.fortran_module.specbfield.get_bfield_many_1d(
                x1arr, x2arr, x3arr, n
            )

        return Blist

    def dBdX_many(self, x1arr, x2arr, x3arr, input1D=True, *args):
        """! Returns magnetic fields
        @param x1arr the first coordinates. Should have the same length as the other two if input1D=True.
        @param x2arr the second coordinates. Should have the same length as the other two if input1D=True.
        @param x3arr the third coordinates. Should have the same length as the other two if input1D=True.
        @param input1D if False, create a meshgrid with sarr, tarr and zarr, if True, treat them as a list of points
        @param *args extra parameters
        @returns B, dBdX, the contravariant magnetic fields, the derivatives of them
        """

        x1arr = np.atleast_1d(x1arr)
        x2arr = np.atleast_1d(x2arr)
        x3arr = np.atleast_1d(x3arr)

        if not input1D:
            size = (x1arr.size, x2arr.size, x3arr.size)
            s = np.broadcast_to(x1arr[:, np.newaxis, np.newaxis], size).flatten()
            t = np.broadcast_to(x2arr[np.newaxis, :, np.newaxis], size).flatten()
            z = np.broadcast_to(x3arr[np.newaxis, np.newaxis, :], size).flatten()
            n = s.size
            Blist, dBlist = self.fortran_module.specbfield.get_bfield_tangent_many_1d(
                s, t, z, n
            )
            Blist = np.reshape(Blist, (x1arr.size, x2arr.size, x3arr.size, 3))
            dBlist = np.reshape(dBlist, (x1arr.size, x2arr.size, x3arr.size, 3, 3))

        else:
            n = x1arr.size
            Blist, dBlist = self.fortran_module.specbfield.get_bfield_tangent_many_1d(
                x1arr, x2arr, x3arr, n
            )

        return Blist, dBlist
    
    def A(self, coords, *args):
        """! Returns the vector potential
        @param coordinates \\f$(s,\\theta,\\zeta)\\f$
        @param *args extra parameters
        @returns the contravariant vector potential
        """
        raise ValueError("Vector potential is not implemented")

        #return self.fortran_module.specbfield.get_vector_potential(coords)

    def convert_coords(self, stz):
        """! Python wrapper for getting the xyz coordinates from stz
        @param stz  the stz coordinate
        @returns the xyz coordinates
        """
        xyz = self.fortran_module.speccoords.get_xyz(stz)

        # depending on the geometry, return RZ or yx
        if self.Igeometry == 1:
            # for a slab, return x=R, y=theta, z=zeta
            return np.array(
                [
                    xyz[0],
                    np.mod(stz[1], 2 * np.pi) * self.rpol,
                    np.mod(stz[2], 2 * np.pi) * self.rtor,
                ],
                dtype=np.float64,
            )
        if self.Igeometry == 2:
            # for cylinderical geometry, return x=r*cos theta, y=zeta*rtor, z=sin theta
            return np.array(
                [xyz[0] * np.cos(stz[1]), stz[2] * self.rtor, xyz[0] * np.sin(stz[1])],
                dtype=np.float64,
            )
        if self.Igeometry == 3:
            # for toroidal geometry, return x=R, y=zeta, z=Z
            return xyz
        

    def _init_fortran_module(self, spec_data, lvol):
        """
        Set up the Fortran module which uses compiled functions to 
        evaluate the fields and their derivatives.
        Arguments: 
        spec_data: SPECout file loaded with the py_spec python package
        lvol: volume number of the field to be evaluated
        """

        self.fortran_module = fortran_module

        # check the version of SPEC output file. Only >=3.0 is accepted
        if spec_data.version < 3.0:
            raise Exception("SPEC version >=3.0 is needed")

        # setting up the fortran module
        fortran_module.specvariables.mvol = spec_data.output.Mvol
        fortran_module.specvariables.ntor = spec_data.input.physics.Ntor
        fortran_module.specvariables.mpol = spec_data.input.physics.Mpol
        fortran_module.specvariables.igeometry = spec_data.input.physics.Igeometry
        fortran_module.specvariables.mn = spec_data.output.mn
        fortran_module.specvariables.notstellsym = (
            spec_data.input.physics.Istellsym == 0
        )
        fortran_module.specvariables.nfp = spec_data.input.physics.Nfp
        fortran_module.specvariables.im = spec_data.output.im
        fortran_module.specvariables.in1 = spec_data.output.in_

        fortran_module.specvariables.irbc = spec_data.output.Rbc.T
        fortran_module.specvariables.izbc = spec_data.output.Zbc.T
        fortran_module.specvariables.irbs = spec_data.output.Rbs.T
        fortran_module.specvariables.izbs = spec_data.output.Zbs.T

        # saving some quantities for self as well
        self.Mvol = spec_data.output.Mvol
        self.Ntor = spec_data.input.physics.Ntor
        self.Mpol = spec_data.input.physics.Mpol
        self.Igeometry = spec_data.input.physics.Igeometry
        self.NOTstellsym = spec_data.input.physics.Istellsym == 0
        self.Nfp = spec_data.input.physics.Nfp

        # rpol and rtol, in case they are not saved into SPEC output
        try:
            self.rpol = spec_data.input.physics.rpol
            self.rtor = spec_data.input.physics.rtor
        except:
            self.rpol = 1.0
            self.rtor = 1.0

        if lvol > 0 and lvol <= spec_data.output.Mvol:
            # setting up the fortran module
            fortran_module.specvariables.rpol = self.rpol
            fortran_module.specvariables.rtor = self.rtor
            fortran_module.specvariables.ivol = lvol
            fortran_module.specvariables.lrad = spec_data.input.physics.Lrad[lvol - 1]
            fortran_module.specvariables.ate = spec_data.vector_potential.Ate[
                lvol - 1
            ].T
            fortran_module.specvariables.ato = spec_data.vector_potential.Ato[
                lvol - 1
            ].T
            fortran_module.specvariables.aze = spec_data.vector_potential.Aze[
                lvol - 1
            ].T
            fortran_module.specvariables.azo = spec_data.vector_potential.Azo[
                lvol - 1
            ].T
            fortran_module.specvariables.lcoordinatesingularity = (
                spec_data.input.physics.Igeometry >= 2 and lvol == 1
            )

            # saving some quantities for self as well
            self.ivol = lvol
            self.Lrad = spec_data.input.physics.Lrad[lvol - 1]
            self.Lcoordinatesingularity = (
                spec_data.input.physics.Igeometry >= 2 and lvol == 1
            )

        else:
            raise Exception("Volume number lvol out of bound")

